import { db, schema } from "../server/db/index.js";
import { assinaturaDeAcesso } from "../server/auth/guard.js";
import { acessoVigente } from "../server/billing/acesso.js";
await new Promise(r => setTimeout(r, 4000));
const u = await db.primeiro(schema.users, { email: "camila@exemplo.com.br" });
const a = await db.primeiro(schema.subscriptions, { userId: u!.id });
await db.atualizar(schema.subscriptions, { id: a!.id }, { currentPeriodEnd: new Date("2025-01-01") });
const a2 = await db.primeiro(schema.subscriptions, { id: a!.id });
console.log("status:", a2!.status, "periodo terminou em:", a2!.currentPeriodEnd);
console.log("acessoVigente:", acessoVigente(a2!));
console.log("assinaturaDeAcesso devolve:", (await assinaturaDeAcesso(u!))?.id === a!.id);
process.exit(0);
